# Generated by Django 2.2.7 on 2020-03-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200331_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
