# Generated by Django 2.2.10 on 2020-04-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200331_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='donation',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
