# Generated by Django 2.2.7 on 2020-04-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_donationbasket_donationbasketitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationbasketitem',
            name='donationbasket_item',
        ),
        migrations.RemoveField(
            model_name='donationbasketitem',
            name='requirement',
        ),
        migrations.DeleteModel(
            name='DonationBasket',
        ),
        migrations.DeleteModel(
            name='DonationBasketItem',
        ),
    ]
