# Generated by Django 2.2.7 on 2020-04-01 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200401_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='DonationBasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationbasket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DonationBasket')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Menu')),
                ('retaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant')),
            ],
        ),
    ]
