# Generated by Django 2.2.7 on 2020-04-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200401_1646'),
        ('api', '0026_donationbasketitem'),
    ]

    operations = [
    ]
