# Generated by Django 2.2.7 on 2020-04-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20200402_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationbasket',
            name='item',
        ),
        migrations.RemoveField(
            model_name='donationbasket',
            name='total_donation',
        ),
        migrations.DeleteModel(
            name='DonationBasketItem',
        ),
    ]
