# Generated by Django 2.2.10 on 2020-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_menu_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationbasket',
            name='total_donations',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donationbasket',
            name='single_restaurant_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
