# Generated by Django 2.2.10 on 2020-04-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200404_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationbasket',
            old_name='total_donations',
            new_name='total_donation_recieved',
        ),
    ]
