# Generated by Django 2.2.10 on 2020-04-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200405_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
