# Generated by Django 2.2.10 on 2020-04-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200406_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
