# Generated by Django 2.2.10 on 2020-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200406_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
