# Generated by Django 2.2.10 on 2020-04-11 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200406_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Donation')),
            ],
        ),
    ]
