# Generated by Django 2.2.10 on 2020-04-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_restaurant_menu_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu_total',
        ),
    ]
